### ISSUE TITLE
Offset conversion is busted

### ISSUE THREAD

**Issue by scholarsmate** [ctc-oss/daffodil-vscode#102]
When there is a value in the offset field, say 77 and the address in "Decimal", then the user changes the address to be "Hexidecimal", then the 77 gets interpreted as hex rather than being _converted_ to hex.  This means that when the address is changed, we need to use the current selection, and the new selection and convert the offset using a function like this one:

```typescript
function convertNumber(num: string, fromRadix: number, toRadix: number): string {
  const parsedNum = parseInt(num, fromRadix);
  return parsedNum.toString(toRadix);
}
```

After the conversion has taken place, then the new selection becomes the current selection so we can handle the next change.  When changing the address, the viewport shouldn't move because the computed offset ought to be the same _count_, just in a different _radix_.

**Comment by stricklandrbls** [comment]
Fixed with commit https://github.com/ctc-oss/daffodil-vscode/commit/4c7645c39731e2edf70206967469a92315078448
