### ISSUE TITLE
Determining Whitespace Vs ASCII Space in Logical View

### ISSUE THREAD

**Issue by stricklandrbls** [ctc-oss/daffodil-vscode#103]
## Issue
Determining whether the user selection, in both simple and full, does not function properly for single byte selections.
### Simple Mode
The `editByteWindow` does not appear when an ASCII space (`0x20`) is selected byte the `isWhitespace` function considers that actual space as part of the index padding.
### Full Mode
Selecting a single byte space causes an infinite loop within the `frameSelectedOnWhitespace`

**Comment by scholarsmate** [comment]
This has been completed.
