### ISSUE TITLE
REQ-EDT-01: The editor shall implement inline editing within a viewport 

### ISSUE THREAD

**Issue by scholarsmate** [ctc-oss/daffodil-vscode#21]
The viewport will support mouse and keyboard interaction to initiate editing a value.

**Comment by Shanedell** [comment]
@scholarsmate This is already supported. It wasn't visible before as the current demo client does not make the viewport editable but just tested with making it editable and it worked as expected. I believe the adding of data works for viewports but deleting it doesn't make the viewport adjust back to previous data
