### ISSUE TITLE
Single 0a (line feed) logical selection crashes the extension

### ISSUE THREAD

**Issue by scholarsmate** [ctc-oss/daffodil-vscode#79]
Reproduction: Load a file that has \r\n in it like `package.json`, then in the logical view, select just a single line feed (0a, decimal 10).  This crashes the extension.

**Comment by stricklandrbls** [comment]
@scholarsmate I haven't seen the extension _crash_ anymore. Do we want to delete this ticket and create another for cleaning up some of the issues for representing `0x0a`?
