### ISSUE TITLE
Search and Replace need to take uint8array

### ISSUE THREAD

**Issue by scholarsmate** [ctc-oss/daffodil-vscode#81]
Currently the Search and Replace functions are taking only `string`, but need to also take `uint8array`.  The front-end needs to have a toggle between the physical and logical views where the search and replace are expected to take place and use the same encoding as the selected view.

**Comment by stricklandrbls** [comment]
Fixed in commit: `3327cf249c94990ccb3d6a67a55becc997eaac8b`. Search utilizes the selected encoding from the content controls to accommodate easier `BufferEncoding` cross references in the extension. The content controls also have a larger amount of encodings.
