### ISSUE TITLE
Add Undo/Redo feature to the Data Editor

### ISSUE THREAD

**Issue by scholarsmate** [ctc-oss/daffodil-vscode#84]
When a commit has been made, enable undo, and enable redo if there is an undo that can be undone.

**Comment by scholarsmate** [comment]
The functions that will enable these features are `getChangeCount`, `getUndoCount` (these are undone changes that can be redone), `undo`, and `redo`.  There is also a `clear` function which can be used to clear all changes if we have the space for another button.  All of these functions are in Ωedit's `change.js` and just take the session id.  Wiring ought to be straightforward.

**Comment by stricklandrbls** [comment]
Implemented in commit https://github.com/ctc-oss/daffodil-vscode/commit/9b5dcbe72848513ae75db1c81a01cc0abe63b893
