### ISSUE TITLE
Data Inspector should stay in decimal

### ISSUE THREAD

**Issue by scholarsmate** [ctc-oss/daffodil-vscode#92]
The Data Inspector right now is tied to the radix selection, but should just remain in decimal all the time.

<img width="1673" alt="Screenshot 2023-02-06 at 2 38 21 PM" src="https://user-images.githubusercontent.com/2205472/217069047-f7bf93f7-828e-477e-970b-92c9439f0640.png">

**Comment by stricklandrbls** [comment]
Fixed in commit https://github.com/ctc-oss/daffodil-vscode/commit/9b5dcbe72848513ae75db1c81a01cc0abe63b893
