### ISSUE TITLE
Clear doesn't appear to clear the redo stack

### ISSUE THREAD

**Issue by scholarsmate** [ctc-oss/daffodil-vscode#93]
It's not yet clear where this bug resides.  I'll check and if necessary add unit tests for this scenario in the Ωedit software stack.  It may require a fix and another Ωedit publish.

**Comment by scholarsmate** [comment]
This is a bug in Ωedit that has been fixed in version 0.9.38.  Once this project merges that update, it should fix this issue.

**Comment by stricklandrbls** [comment]
Implemented in commit https://github.com/ctc-oss/daffodil-vscode/commit/9b5dcbe72848513ae75db1c81a01cc0abe63b893
